/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { TopologySnapshot } from '@qidiai/dsh-contrib-topology/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$746f706f6c6f6779 {
    graph: () => Promise<RemoteResult<TopologySnapshot>>
  }
  interface TypertRemoteMap {
    'topology/graph': () => Promise<RemoteResult<TopologySnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'topology': TypertRemoteNamespace$746f706f6c6f6779
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
