/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_contrib_orchestrator_orchestrator_dispatch_parameter_0$schema = z.object({
  'task': z.string().readonly(),
  'agents': z.array(z.string()).readonly().optional(),
  'mode': z.union([z.literal("parallel"), z.literal("sequential"), z.literal("select"), z.literal("cascade"), z.literal("merge")]).readonly().optional(),
  'parallelLimit': z.number().readonly().optional(),
  'retryCount': z.number().readonly().optional(),
  'routeHint': z.string().readonly().optional(),
  'parentSessionId': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_contrib_orchestrator_orchestrator_dispatch_result$schema = z.object({
  'task': z.string().readonly(),
  'mode': z.union([z.literal("parallel"), z.literal("sequential"), z.literal("select"), z.literal("cascade"), z.literal("merge")]).readonly(),
  'runs': z.array(z.object({
  'agent': z.string().readonly(),
  'ok': z.boolean().readonly(),
  'durationMs': z.number().readonly(),
  'error': z.string().readonly().optional(),
})).readonly(),
  'winner': z.string().readonly().optional(),
  'allOk': z.boolean().readonly(),
  'startedAt': z.string().readonly(),
  'durationMs': z.number().readonly(),
  'ranked': z.array(z.object({
  'agent': z.string().readonly(),
  'score': z.number().readonly(),
  'reason': z.string().readonly(),
  'coolingDown': z.boolean().readonly(),
})).readonly().optional(),
})
const _deepseek_ai_dsh_contrib_orchestrator_orchestrator_snapshot_result$schema = z.object({
  'stats': z.object({
  'dispatches': z.number().readonly(),
  'runs': z.number().readonly(),
  'successes': z.number().readonly(),
  'failures': z.number().readonly(),
  'byMode': z.record(z.string(), z.number()).readonly(),
}).readonly(),
  'history': z.array(z.object({
  'startedAt': z.string().readonly(),
  'task': z.string().readonly(),
  'mode': z.union([z.literal("parallel"), z.literal("sequential"), z.literal("select"), z.literal("cascade"), z.literal("merge")]).readonly(),
  'winner': z.string().readonly().optional(),
  'allOk': z.boolean().readonly(),
  'durationMs': z.number().readonly(),
})).readonly(),
  'capturedAt': z.string().readonly(),
})
const _deepseek_ai_dsh_contrib_orchestrator_orchestrator_stats_result$schema = z.object({
  'dispatches': z.number().readonly(),
  'runs': z.number().readonly(),
  'successes': z.number().readonly(),
  'failures': z.number().readonly(),
  'byMode': z.record(z.string(), z.number()).readonly(),
})

export const TYPERT = {
  package: '@qidiai/dsh-contrib-orchestrator',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@qidiai/dsh-contrib-orchestrator#orchestrator/dispatch',
      service: 'orchestrator',
      namespace: 'orchestrator',
      method: 'dispatch',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qidiai/dsh-contrib-orchestrator/types#OrchestratorRequest',
            schema: _deepseek_ai_dsh_contrib_orchestrator_orchestrator_dispatch_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qidiai/dsh-contrib-orchestrator/types#OrchestratorResult',
        schema: _deepseek_ai_dsh_contrib_orchestrator_orchestrator_dispatch_result$schema,
      },
      sourceLocation: {"file":"packages/contrib/orchestrator/src/host/index.ts","line":58,"column":9},
    },
    {
      id: '@qidiai/dsh-contrib-orchestrator#orchestrator/snapshot',
      service: 'orchestrator',
      namespace: 'orchestrator',
      method: 'snapshot',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qidiai/dsh-contrib-orchestrator/types#OrchestratorSnapshot',
        schema: _deepseek_ai_dsh_contrib_orchestrator_orchestrator_snapshot_result$schema,
      },
      sourceLocation: {"file":"packages/contrib/orchestrator/src/host/index.ts","line":166,"column":3},
    },
    {
      id: '@qidiai/dsh-contrib-orchestrator#orchestrator/stats',
      service: 'orchestrator',
      namespace: 'orchestrator',
      method: 'stats',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qidiai/dsh-contrib-orchestrator/types#OrchestratorStats',
        schema: _deepseek_ai_dsh_contrib_orchestrator_orchestrator_stats_result$schema,
      },
      sourceLocation: {"file":"packages/contrib/orchestrator/src/host/index.ts","line":154,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
