/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { OrchestratorRequest, OrchestratorResult, OrchestratorSnapshot, OrchestratorStats } from '@qidiai/dsh-contrib-orchestrator/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6f7263686573747261746f72 {
    dispatch: (request: OrchestratorRequest) => Promise<RemoteResult<OrchestratorResult>>
    probe: () => Promise<RemoteResult<{ agents: string; subagents: string; hasInitiator: boolean; }>>
    snapshot: () => Promise<RemoteResult<OrchestratorSnapshot>>
    stats: () => Promise<RemoteResult<OrchestratorStats>>
  }
  interface TypertRemoteMap {
    'orchestrator/dispatch': (request: OrchestratorRequest) => Promise<RemoteResult<OrchestratorResult>>
    'orchestrator/probe': () => Promise<RemoteResult<{ agents: string; subagents: string; hasInitiator: boolean; }>>
    'orchestrator/snapshot': () => Promise<RemoteResult<OrchestratorSnapshot>>
    'orchestrator/stats': () => Promise<RemoteResult<OrchestratorStats>>
  }
  interface TypertRemoteNamespaceMap {
    'orchestrator': TypertRemoteNamespace$6f7263686573747261746f72
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
