/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { DashboardStatus } from '@qidiai/dsh-contrib-dashboard/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$64617368626f617264 {
    status: () => Promise<RemoteResult<DashboardStatus>>
  }
  interface TypertRemoteMap {
    'dashboard/status': () => Promise<RemoteResult<DashboardStatus>>
  }
  interface TypertRemoteNamespaceMap {
    'dashboard': TypertRemoteNamespace$64617368626f617264
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
