/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_contrib_router_router_profiles_result$schema = z.object({
  'providers': z.array(z.object({
  'name': z.string().readonly(),
  'id': z.string().readonly(),
  'canonicalId': z.string().readonly(),
  'calls': z.number().readonly(),
  'successes': z.number().readonly(),
  'weightedCalls': z.number().readonly(),
  'weightedSuccesses': z.number().readonly(),
  'successScore': z.number().readonly(),
  'stabilityScore': z.number().readonly(),
  'confidence': z.number().readonly(),
  'freshness': z.number().readonly(),
  'averageDurationMs': z.union([z.literal(null), z.number()]).readonly(),
  'averageTokens': z.union([z.literal(null), z.number()]).readonly(),
  'lastObservedAt': z.union([z.literal(null), z.string()]).readonly(),
  'lastSuccessAt': z.union([z.literal(null), z.string()]).readonly(),
  'lastFailureAt': z.union([z.literal(null), z.string()]).readonly(),
  'cooldownUntil': z.union([z.literal(null), z.string()]).readonly(),
  'coolingDown': z.boolean().readonly(),
})).readonly(),
  'capturedAt': z.string().readonly(),
})
const _deepseek_ai_dsh_contrib_router_router_rank_parameter_0$schema = z.string()
const _deepseek_ai_dsh_contrib_router_router_rank_parameter_1$schema = z.union([z.undefined(), z.array(z.string())])
const _deepseek_ai_dsh_contrib_router_router_rank_result$schema = z.object({
  'task': z.string().readonly(),
  'category': z.string().readonly(),
  'ranked': z.array(z.object({
  'name': z.string().readonly(),
  'score': z.number().readonly(),
  'category': z.string().readonly(),
  'components': z.record(z.string(), z.number()).readonly(),
  'explorationBonus': z.number().readonly(),
  'reason': z.string().readonly(),
  'profile': z.object({
  'name': z.string().readonly(),
  'id': z.string().readonly(),
  'canonicalId': z.string().readonly(),
  'calls': z.number().readonly(),
  'successes': z.number().readonly(),
  'weightedCalls': z.number().readonly(),
  'weightedSuccesses': z.number().readonly(),
  'successScore': z.number().readonly(),
  'stabilityScore': z.number().readonly(),
  'confidence': z.number().readonly(),
  'freshness': z.number().readonly(),
  'averageDurationMs': z.union([z.literal(null), z.number()]).readonly(),
  'averageTokens': z.union([z.literal(null), z.number()]).readonly(),
  'lastObservedAt': z.union([z.literal(null), z.string()]).readonly(),
  'lastSuccessAt': z.union([z.literal(null), z.string()]).readonly(),
  'lastFailureAt': z.union([z.literal(null), z.string()]).readonly(),
  'cooldownUntil': z.union([z.literal(null), z.string()]).readonly(),
  'coolingDown': z.boolean().readonly(),
}).readonly(),
})).readonly(),
  'capturedAt': z.string().readonly(),
})

export const TYPERT = {
  package: '@qidiai/dsh-contrib-router',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@qidiai/dsh-contrib-router#router/profiles',
      service: 'router',
      namespace: 'router',
      method: 'profiles',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qidiai/dsh-contrib-router/types#RouterSnapshot',
        schema: _deepseek_ai_dsh_contrib_router_router_profiles_result$schema,
      },
      sourceLocation: {"file":"packages/contrib/router/src/host/index.ts","line":90,"column":3},
    },
    {
      id: '@qidiai/dsh-contrib-router#router/rank',
      service: 'router',
      namespace: 'router',
      method: 'rank',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'task',
          wire: 'task',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qidiai/dsh-contrib-router#router/rank:task',
            schema: _deepseek_ai_dsh_contrib_router_router_rank_parameter_0$schema,
          },
        },
        {
          name: 'candidates',
          wire: 'candidates',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@qidiai/dsh-contrib-router#router/rank:candidates',
            schema: _deepseek_ai_dsh_contrib_router_router_rank_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qidiai/dsh-contrib-router/types#RouterRankResult',
        schema: _deepseek_ai_dsh_contrib_router_router_rank_result$schema,
      },
      sourceLocation: {"file":"packages/contrib/router/src/host/index.ts","line":103,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
