/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { RouterRankResult, RouterSnapshot } from '@deepseek-ai/dsh-contrib-router/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$726f75746572 {
    profiles: () => Promise<RemoteResult<RouterSnapshot>>
    rank: (task: string, candidates?: readonly string[]) => Promise<RemoteResult<RouterRankResult>>
  }
  interface TypertRemoteMap {
    'router/profiles': () => Promise<RemoteResult<RouterSnapshot>>
    'router/rank': (task: string, candidates?: readonly string[]) => Promise<RemoteResult<RouterRankResult>>
  }
  interface TypertRemoteNamespaceMap {
    'router': TypertRemoteNamespace$726f75746572
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
