/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_contrib_mcp_bridge_mcp_bridge_addServer_parameter_0$schema = z.object({
  'serverName': z.string().readonly(),
  'transport': z.union([z.literal("stdio"), z.literal("streamable-http")]).readonly(),
  'command': z.string().readonly().optional(),
  'args': z.array(z.string()).readonly().optional(),
  'url': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_contrib_mcp_bridge_mcp_bridge_addServer_result$schema = z.object({
  'servers': z.array(z.object({
  'serverName': z.string().readonly(),
  'status': z.union([z.literal("connected"), z.literal("reconnecting"), z.literal("failed"), z.literal("stopped")]).readonly(),
  'toolCount': z.number().readonly(),
  'lastError': z.string().readonly().optional(),
  'updatedAt': z.string().readonly(),
})).readonly(),
  'capturedAt': z.string().readonly(),
})
const _deepseek_ai_dsh_contrib_mcp_bridge_mcp_bridge_probe_result$schema = z.object({
  'hasToolsIn': z.boolean().readonly(),
  'getTools': z.string().readonly(),
  'propsKeys': z.array(z.string()).readonly(),
  'hasToolsProp': z.boolean().readonly(),
  'provideOutcome': z.string().readonly(),
  'postHasToolsProp': z.boolean().readonly(),
  'fiberRuntime': z.string().readonly(),
  'extendChildGetTools': z.string().readonly(),
  'extendChildHasToolsIn': z.boolean().readonly(),
})
const _deepseek_ai_dsh_contrib_mcp_bridge_mcp_bridge_removeServer_parameter_0$schema = z.string()
const _deepseek_ai_dsh_contrib_mcp_bridge_mcp_bridge_removeServer_result$schema = z.object({
  'servers': z.array(z.object({
  'serverName': z.string().readonly(),
  'status': z.union([z.literal("connected"), z.literal("reconnecting"), z.literal("failed"), z.literal("stopped")]).readonly(),
  'toolCount': z.number().readonly(),
  'lastError': z.string().readonly().optional(),
  'updatedAt': z.string().readonly(),
})).readonly(),
  'capturedAt': z.string().readonly(),
})
const _deepseek_ai_dsh_contrib_mcp_bridge_mcp_bridge_snapshot_result$schema = z.object({
  'servers': z.array(z.object({
  'serverName': z.string().readonly(),
  'status': z.union([z.literal("connected"), z.literal("reconnecting"), z.literal("failed"), z.literal("stopped")]).readonly(),
  'toolCount': z.number().readonly(),
  'lastError': z.string().readonly().optional(),
  'updatedAt': z.string().readonly(),
})).readonly(),
  'capturedAt': z.string().readonly(),
})

export const TYPERT = {
  package: '@qidiai/dsh-contrib-mcp-bridge',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@qidiai/dsh-contrib-mcp-bridge#mcp-bridge/addServer',
      service: 'mcp-bridge',
      namespace: 'mcp-bridge',
      method: 'addServer',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'server',
          wire: 'server',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qidiai/dsh-contrib-mcp-bridge/types#McpServerConfig',
            schema: _deepseek_ai_dsh_contrib_mcp_bridge_mcp_bridge_addServer_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qidiai/dsh-contrib-mcp-bridge/types#BridgeSnapshot',
        schema: _deepseek_ai_dsh_contrib_mcp_bridge_mcp_bridge_addServer_result$schema,
      },
      sourceLocation: {"file":"packages/contrib/mcp-bridge/src/host/index.ts","line":230,"column":9},
    },
    {
      id: '@qidiai/dsh-contrib-mcp-bridge#mcp-bridge/probe',
      service: 'mcp-bridge',
      namespace: 'mcp-bridge',
      method: 'probe',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qidiai/dsh-contrib-mcp-bridge/types#BridgeProbe',
        schema: _deepseek_ai_dsh_contrib_mcp_bridge_mcp_bridge_probe_result$schema,
      },
      sourceLocation: {"file":"packages/contrib/mcp-bridge/src/host/index.ts","line":174,"column":3},
    },
    {
      id: '@qidiai/dsh-contrib-mcp-bridge#mcp-bridge/removeServer',
      service: 'mcp-bridge',
      namespace: 'mcp-bridge',
      method: 'removeServer',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'serverName',
          wire: 'serverName',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qidiai/dsh-contrib-mcp-bridge#mcp-bridge/removeServer:serverName',
            schema: _deepseek_ai_dsh_contrib_mcp_bridge_mcp_bridge_removeServer_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qidiai/dsh-contrib-mcp-bridge/types#BridgeSnapshot',
        schema: _deepseek_ai_dsh_contrib_mcp_bridge_mcp_bridge_removeServer_result$schema,
      },
      sourceLocation: {"file":"packages/contrib/mcp-bridge/src/host/index.ts","line":245,"column":3},
    },
    {
      id: '@qidiai/dsh-contrib-mcp-bridge#mcp-bridge/snapshot',
      service: 'mcp-bridge',
      namespace: 'mcp-bridge',
      method: 'snapshot',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qidiai/dsh-contrib-mcp-bridge/types#BridgeSnapshot',
        schema: _deepseek_ai_dsh_contrib_mcp_bridge_mcp_bridge_snapshot_result$schema,
      },
      sourceLocation: {"file":"packages/contrib/mcp-bridge/src/host/index.ts","line":159,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
