/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_contrib_observe_observe_clear_result$schema = z.void()
const _deepseek_ai_dsh_contrib_observe_observe_snapshot_result$schema = z.object({
  'events': z.array(z.object({
  'id': z.string().readonly(),
  'kind': z.union([z.literal("tool.call"), z.literal("llm.stream")]).readonly(),
  'name': z.string().readonly(),
  'agent': z.string().readonly().optional(),
  'startedAt': z.string().readonly(),
  'durationMs': z.number().readonly().optional(),
  'outcome': z.union([z.literal("success"), z.literal("error"), z.literal("cancelled")]).readonly(),
  'source': z.union([z.literal("builtin"), z.literal("mcp")]).readonly(),
  'features': z.record(z.string(), z.union([z.string(), z.number(), z.literal(false), z.literal(true)])).readonly().optional(),
})).readonly(),
  'stats': z.object({
  'totalEvents': z.number().readonly(),
  'toolCalls': z.number().readonly(),
  'llmStreams': z.number().readonly(),
  'errorCount': z.number().readonly(),
  'droppedCount': z.number().readonly(),
}).readonly(),
  'capturedAt': z.string().readonly(),
})
const _deepseek_ai_dsh_contrib_observe_observe_stats_result$schema = z.object({
  'totalEvents': z.number().readonly(),
  'toolCalls': z.number().readonly(),
  'llmStreams': z.number().readonly(),
  'errorCount': z.number().readonly(),
  'droppedCount': z.number().readonly(),
})

export const TYPERT = {
  package: '@qidiai/dsh-contrib-observe',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@qidiai/dsh-contrib-observe#observe/clear',
      service: 'observe',
      namespace: 'observe',
      method: 'clear',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qidiai/dsh-contrib-observe#observe/clear:result',
        schema: _deepseek_ai_dsh_contrib_observe_observe_clear_result$schema,
      },
      sourceLocation: {"file":"packages/contrib/observe/src/host/index.ts","line":180,"column":3},
    },
    {
      id: '@qidiai/dsh-contrib-observe#observe/snapshot',
      service: 'observe',
      namespace: 'observe',
      method: 'snapshot',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qidiai/dsh-contrib-observe/types#ObserveSnapshot',
        schema: _deepseek_ai_dsh_contrib_observe_observe_snapshot_result$schema,
      },
      sourceLocation: {"file":"packages/contrib/observe/src/host/index.ts","line":168,"column":3},
    },
    {
      id: '@qidiai/dsh-contrib-observe#observe/stats',
      service: 'observe',
      namespace: 'observe',
      method: 'stats',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qidiai/dsh-contrib-observe/types#ObserveStats',
        schema: _deepseek_ai_dsh_contrib_observe_observe_stats_result$schema,
      },
      sourceLocation: {"file":"packages/contrib/observe/src/host/index.ts","line":174,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
