/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ObserveSnapshot, ObserveStats } from '@deepseek-ai/dsh-contrib-observe/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6f627365727665 {
    clear: () => Promise<RemoteResult<void>>
    snapshot: () => Promise<RemoteResult<ObserveSnapshot>>
    stats: () => Promise<RemoteResult<ObserveStats>>
  }
  interface TypertRemoteMap {
    'observe/clear': () => Promise<RemoteResult<void>>
    'observe/snapshot': () => Promise<RemoteResult<ObserveSnapshot>>
    'observe/stats': () => Promise<RemoteResult<ObserveStats>>
  }
  interface TypertRemoteNamespaceMap {
    'observe': TypertRemoteNamespace$6f627365727665
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
