/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_contrib_dashboard_dashboard_status_result$schema = z.object({
  'topology': z.object({
  'ok': z.boolean(),
  'detail': z.string(),
}).readonly(),
  'observe': z.object({
  'ok': z.boolean(),
  'detail': z.string(),
}).readonly(),
  'router': z.object({
  'ok': z.boolean(),
  'detail': z.string(),
}).readonly(),
  'orchestrator': z.object({
  'ok': z.boolean(),
  'detail': z.string(),
}).readonly(),
  'mcpBridge': z.object({
  'ok': z.boolean(),
  'detail': z.string(),
}).readonly(),
  'capturedAt': z.string().readonly(),
})

export const TYPERT = {
  package: '@qidiai/dsh-contrib-dashboard',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@qidiai/dsh-contrib-dashboard#dashboard/status',
      service: 'dashboard',
      namespace: 'dashboard',
      method: 'status',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qidiai/dsh-contrib-dashboard/types#DashboardStatus',
        schema: _deepseek_ai_dsh_contrib_dashboard_dashboard_status_result$schema,
      },
      sourceLocation: {"file":"packages/contrib/dashboard/src/host/index.ts","line":26,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
